= Process instructions
[horizontal]

== About the process
Peppol BIS Advanced Ordering is made up of a set of subprocesses that allow both the buyer and the seller to make changes or cancellations to an order. The subprocesses are:

*Buyer's processes*

* Place initial order  
* Change the order  
* Cancel the order  

*Seller's processes*

* Change the order  
* Cancel the order  

However, in the context of trade with Singapore government buyers using this BIS, the seller is not allowed to use electonic messages through Peppol to change or cancel an order after it has been placed. Only the buyer has the possibility to manage the order after submission, which includes, making changes or cancelling the initital order.  

For these actions, the following Peppol transactions are used by the buyer:

* To place the initial order - *Peppol Order transaction (T01)*.  
* To cancel an order - *Peppol Order Cancellation transaction (T115)* .  
* To change an order - *Peppol Order Change transaction (T114)*.  


NOTE:
****
When the *seller* needs to change or cancel an order, they must contact the buyer directly using contact channels defined in their contract (such as by phone or email).
****


TIP:
****
When the *seller* needs to change or cancel an order, they must contact the buyer directly using contact channels defined in their contract (such as by phone or email).
****


== Responding to the order
There




