= The Process Flow
[horizontal]

== Specific process instructions

In B2G transactions using Advance Ordering , the vendor shall not send electronic messages through Peppol to propose changes or cancellations after an order has been sent by the buyer. Only the buyer can manage the order after submission, including making changes or cancelling the initial order.

For these actions, only the following Peppol transactions are used:

* Buyer placing the initial order - *Peppol Order transaction (T01)*.
* Buyer cancelling an order - *Peppol Order Cancellation transaction (T115)*.
* Buyer changing an order - *Peppol Order Change transaction (T114)*.

Consequently, the following Peppol transaction *should not be used*:

* Seller cancelling an order - *Peppol Order Response Advanced transaction (T116)*
* Seller changing an order - *Peppol Order Response Advanced transaction (T116)*


****
NOTE: If the *vendor* needs to propose a change or cancel an order, they must contact the buyer directly using contact channels defined in their contract (such as by phone or email).
****

== Responding to the order
Peppol Advanced Ordering defines how the vendor can respond to the Order, Order Change, and Order Cancellation using the Order Response message. However, order response is currently not supported for B2G transaction. Vendors should not send order responses on InvoiceNow for B2G transactions.

****
NOTE: If the *vendor* can't accept an order, they must contact the buyer directly using contact channels defined in their contract (such as by phone or email).
****

****
NOTE: If the *vendor* accepts the order, no response is needed. The order is considered accepted unless the vendor contacts the buyer to state otherwise.
****


