= The Process Flow
[horizontal]
== Advanced ordering general process steps

Peppol BIS Advanced Ordering consists of subprocesses that allow both the buyer and the seller to make changes or cancellations to an order. These subprocesses are:

*Buyer's processes*

* Place initial order
* Change the order
* Cancel the order

*Seller's processes*

* Change the order
* Cancel the order

== Specific process instructions

In trade with Singapore government buyers using this BIS, the seller is not allowed to send electronic messages through Peppol to propose changes or cancellations after an order has been placed. Only the buyer can manage the order after submission, including making changes or cancelling the initial order.

For these actions, only the following Peppol transactions are used:

* Buyer placing the initial order - *Peppol Order transaction (T01)*.
* Buyer cancelling an order - *Peppol Order Cancellation transaction (T115)*.
* Buyer changing an order - *Peppol Order Change transaction (T114)*.

Consequently, the following Peppol transaction *should not be used*:

* Seller cancelling an order - *Peppol Order Response Advanced transaction (T116)*
* Seller changing an order - *Peppol Order Response Advanced transaction (T116)*


****
NOTE: If the *seller* needs to propose a change or cancel an order, they must contact the buyer directly using contact channels defined in their contract (such as by phone or email).
****

== Responding to the order
Peppol BIS Advanced Ordering defines how the seller can respond to the Order, Order Change, and Order Cancellation using the Order Response message. However, Singapore government buyers do not currently support receiving Order Responses, and sellers should therefore not send these as electronic messages.

****
NOTE: If the *seller* can't accept an order, they must contact the buyer directly using contact channels defined in their contract (such as by phone or email).
****

****
NOTE: If the *seller* accepts the order, no response is needed. The order is considered accepted unless the seller contacts the buyer to state otherwise.
****


