= About these specifications

These specifications consists of several components which can be accessed on this website. Here follows a short introduction of each part and its purpose. They can all be accessed from the main page.

== Documentation
The main BIS document (Business Interoperability Specification) which describes a business process and the functionality that it supports. It gives a high level view but also goes also into selected parts of the business message by describing common examples, datatypes and code lists. A business process consists of a series of transaction that are exchanged between the business parties in the described sequence. Technical details for each transaction are provided in the following sections, syntax, rules and code lists.

****
NOTE:It should be noted that these specifications are a re-publication of the same specifications published by OpenPeppol with a few customized non-normative examples that show typical values used in Singapore. The schematron rules are also re-published. In the unlikely event of discrepencies, the OpenPeppol schematron is to be considered normative.
****

== Syntax
An description of each XML element and attribute in the technical format used to represent the business document 

== Rules
Many business rules described in this specification can be automatically evaluated using Schematron. The rules are organized and divided into three files:

== Codelists
Links to each code list being used in the specification. 

== Downloads - Schematron files
A zip-file containing the three groups of schematron rules.

== Downloads - Presentation stylesheet
A zip-file containing the visualization stylesheet which can be used to present the eInvoice in a human-readable form.

== Downloads - Example files
A zip-file containing example files which illustrates common situations.
 

